#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# wikiTaTa — Linux Onboarding
# Runs after clawd issues your activation token (spec card 751f1c4d).
# start.wikitata.com/onboard generates the personalized one-liner that sets
# WT_ACTIVATION_TOKEN, WT_USERNAME, WT_SB_URL before calling this.
#
# Usage (generated by start page — DO NOT run without those env vars):
#   WT_ACTIVATION_TOKEN="..." WT_USERNAME="..." WT_SB_URL="..." \
#     bash <(curl -fsSL https://start.wikitata.com/onboard-linux.sh)
#
# Self-healing: every stage retries on failure, traces the cause, and
# attempts an automatic fix before surfacing an inline confirm prompt.
# NOTHING proceeds silently on error. NOTHING is auto-confirmed destructive.
# Every configured service is written to user_service_configs in the DB
# AND to ~/.config/wikitata/install.jsonl locally (both are truth).
# ═══════════════════════════════════════════════════════════════════════════════

set -uo pipefail

# ── Globals ──────────────────────────────────────────────────────────────────
WT_USERNAME="${WT_USERNAME:-}"
WT_ACTIVATION_TOKEN="${WT_ACTIVATION_TOKEN:-}"
WT_DEVICE_ID=""
WT_SB_URL="${WT_SB_URL:-https://onoujmfhlrhvcqzjniei.supabase.co}"
WT_SB_ANON_KEY="${WT_SB_ANON_KEY:-}"
WT_NODE_VERSION="${WT_NODE_VERSION:-20}"
WT_MCP_REPO="${WT_MCP_REPO:-https://github.com/wikiTaTa/wikitata.git}"
WT_CONFIG_DIR="$HOME/.config/wikitata"
WT_LOCAL_LOG="$WT_CONFIG_DIR/install.jsonl"
PLATFORM="linux"
STAGE=0
TOTAL=13
ERRORS=0
PKG_MGR=""
PKG_INSTALL=""
DISTRO=""

# ── Colors ───────────────────────────────────────────────────────────────────
R='\033[0;31m'; G='\033[0;32m'; Y='\033[0;33m'
C='\033[0;36m'; D='\033[2m';    BD='\033[1m';  RST='\033[0m'
OK="${G}✓${RST}"; FAIL="${R}✗${RST}"; WARN="${Y}⚠${RST}"; ARROW="${C}→${RST}"

# ── Helpers ──────────────────────────────────────────────────────────────────
ok()    { printf "  ${OK}  %s\n" "$1"; }
fail()  { printf "  ${FAIL}  %s\n" "$1" >&2; ERRORS=$((ERRORS + 1)); }
warn()  { printf "  ${WARN}  %s\n" "$1"; }
info()  { printf "  ${ARROW}  %s\n" "$1"; }
dim()   { printf "  ${D}%s${RST}\n" "$1"; }
blank() { echo ""; }
has()   { command -v "$1" >/dev/null 2>&1; }
die()   { printf "\n  ${R}${BD}FATAL: %s${RST}\n\n" "$1" >&2; exit 1; }

step_header() {
  STAGE=$((STAGE + 1))
  clear
  printf "\n\n"
  printf "  ${D}══════════════════════════════════════════════════════════════${RST}\n"
  printf "  ${BD}wikiTaTa Onboarding — Linux${RST}  ${D}step %d of %d${RST}\n" "$STAGE" "$TOTAL"
  printf "  ${D}══════════════════════════════════════════════════════════════${RST}\n\n"
  printf "  ${BD}${C}%s${RST}\n" "$1"
  printf "  ${D}%s${RST}\n\n" "$2"
}

confirm() {
  blank
  printf "  ${Y}${BD}%s${RST}\n" "${1:-Proceed?}"
  printf "  [yes / no]: "
  read -r _REPLY
  case "$_REPLY" in yes|y) return 0 ;; *) return 1 ;; esac
}

log_local() {
  local stage="$1" status="$2" detail="${3:-}"
  mkdir -p "$WT_CONFIG_DIR"
  printf '{"ts":"%s","stage":"%s","status":"%s","detail":"%s","platform":"%s","user":"%s"}\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$stage" "$status" "$detail" "$PLATFORM" "$WT_USERNAME" \
    >> "$WT_LOCAL_LOG" 2>/dev/null || true
}

wt_svc_upsert() {
  # Write a service row to user_service_configs via Supabase REST.
  # Best-effort — logs locally on failure, never blocks install.
  # Post-activation: device_id set but no JWT, so REST calls fail gracefully to local log.
  local svc="$1" port="${2:-null}" path="${3:-null}" status="${4:-active}" detail="${5:-}"
  [ -z "$WT_DEVICE_ID" ] && {
    log_local "db:$svc" "skipped" "no_device"; return 0
  }
  local payload
  payload=$(printf '{"service":"%s","port":%s,"local_path":"%s","status":"%s","created_by":"%s","config":{"detail":"%s","platform":"%s"}}' \
    "$svc" "$port" "$path" "$status" "$WT_USERNAME" "$detail" "$PLATFORM")
  if curl -sf --max-time 10 \
       -X POST "${WT_SB_URL}/rest/v1/user_service_configs" \
       -H "apikey: ${WT_SB_ANON_KEY}" \
       -H "Content-Type: application/json" \
       -H "Prefer: resolution=merge-duplicates" \
       -d "$payload" >/dev/null 2>&1; then
    log_local "db:$svc" "ok" "$detail"
  else
    warn "DB write queued locally for $svc (network/auth — will retry on reconnect)"
    log_local "db:$svc" "queued" "$detail"
  fi
}

retry() {
  # retry <attempts> <initial_delay_s> <command...>
  local attempts="$1" delay="$2"; shift 2
  local i=1
  while [ "$i" -le "$attempts" ]; do
    if "$@"; then return 0; fi
    if [ "$i" -lt "$attempts" ]; then
      warn "Attempt $i/$attempts failed — retrying in ${delay}s..."
      sleep "$delay"
      delay=$((delay * 2))
    fi
    i=$((i + 1))
  done
  return 1
}

find_free_port() {
  local start="${1:-3000}" end="${2:-3099}"
  for p in $(seq "$start" "$end"); do
    if ! ss -tlnp 2>/dev/null | grep -q ":${p} " && \
       ! lsof -ti:"$p" >/dev/null 2>&1; then
      echo "$p"; return 0
    fi
  done
  die "No free port in range $start–$end. Check running services with: ss -tlnp"
}

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 0 — Identity & Prerequisites
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Identity & Prerequisites" \
  "Verifying your wt-demo credentials and environment"

[ -n "$WT_USERNAME" ] || die \
  "WT_USERNAME not set. Run the personalized command from start.wikitata.com/onboard"
[ -n "$WT_ACTIVATION_TOKEN" ] || die \
  "WT_ACTIVATION_TOKEN not set. Follow the activation link in your welcome email."

ok "Username: $WT_USERNAME"
ok "Platform: Linux"

# Generate selfheal token early so we can register its hash atomically with device activation.
SELFHEAL_TOKEN_FILE="$WT_CONFIG_DIR/selfheal-token"
if [ ! -s "$SELFHEAL_TOKEN_FILE" ]; then
  mkdir -p "$WT_CONFIG_DIR"
  umask 077
  openssl rand -hex 32 > "$SELFHEAL_TOKEN_FILE" 2>/dev/null \
    || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "$SELFHEAL_TOKEN_FILE"
  chmod 600 "$SELFHEAL_TOKEN_FILE"
fi
SELFHEAL_HASH=$(tr -d '\n' < "$SELFHEAL_TOKEN_FILE" | sha256sum | cut -d' ' -f1)

# Exchange activation token → device_id + CACP token (one-time; token consumed on
# success). S549: the response is the ONLY delivery of the CACP coordination token
# (anon bootstrap RPC revoked) — capture it NOW or it is lost until a new invite.
# Payload travels over stdin, never argv (ps must not see the token).
info "Validating activation token with wikiTaTa..."
_HOSTNAME="$(hostname 2>/dev/null || echo unknown)"
ACTIVATE_RESP=$(printf '{"token":"%s","username":"%s","mode":"installer","selfheal_token_hash":"%s","hostname":"%s","platform":"linux","device_label":"%s"}' \
    "${WT_ACTIVATION_TOKEN}" "${WT_USERNAME}" "${SELFHEAL_HASH}" "${_HOSTNAME}" "${_HOSTNAME}" \
  | curl -sf --max-time 25 \
  -X POST "${WT_SB_URL}/functions/v1/activate" \
  -H "Content-Type: application/json" --data-binary @- \
  2>/dev/null) || die \
  "Could not reach wikiTaTa activation server. Check your internet connection and try again."

ACTIVATE_OK=$(printf '%s' "$ACTIVATE_RESP" | grep -o '"ok":true' || true)
[ -n "$ACTIVATE_OK" ] || {
  ACTIVATE_ERR=$(printf '%s' "$ACTIVATE_RESP" | grep -oE '"error":"[^"]+"' | head -1)
  die "Activation failed. ${ACTIVATE_ERR:-Check your link or request a new one at start.wikitata.com/request-token}"
}

WT_DEVICE_ID=$(printf '%s' "$ACTIVATE_RESP" | grep -oE '"device_id":"[0-9a-f-]+"' | grep -oE '[0-9a-f-]{36}' | head -1)
[ -n "$WT_DEVICE_ID" ] || die "Activation response missing device_id — contact support."

if printf '%s' "$ACTIVATE_RESP" | grep -q '"device_registered":true'; then
  ok "Activation confirmed — device registered (${WT_DEVICE_ID})"
else
  ok "Activation confirmed — device registration completes in your first Claude session"
fi
log_local "stage0" "activated" "device:${WT_DEVICE_ID}"

# CACP coordination token → config dir (0600). Never echoed, never in argv.
WT_CACP_TMP=$(printf '%s' "$ACTIVATE_RESP" | grep -oE '"cacp_token":"[0-9a-f]+"' | grep -oE '[0-9a-f]{64}' | head -1)
if [ -n "$WT_CACP_TMP" ]; then
  ( umask 077 && printf '%s\n' "$WT_CACP_TMP" > "$WT_CONFIG_DIR/cacp-token" )
  unset WT_CACP_TMP
  ok "CACP coordination token stored ($WT_CONFIG_DIR/cacp-token)"
  log_local "stage0" "cacp_stored" "file:$WT_CONFIG_DIR/cacp-token"
else
  warn "CACP token not delivered — coordination features need a re-issued invite"
  log_local "stage0" "cacp_missing" ""
fi
ACTIVATE_RESP=""

# Check root — refuse to run as root (security)
[ "$(id -u)" != "0" ] || die \
  "Do not run as root. Log in as your regular user account."

# Filesystem write probe — we record what we can and can't touch
FS_HOME_WRITE=false; FS_USR_LOCAL=false; FS_OPT=false
touch "$HOME/.wt_write_probe_$$" 2>/dev/null && { FS_HOME_WRITE=true; rm -f "$HOME/.wt_write_probe_$$"; }
touch /usr/local/.wt_probe_$$ 2>/dev/null && { FS_USR_LOCAL=true; rm -f /usr/local/.wt_probe_$$; } || true
touch /opt/.wt_probe_$$ 2>/dev/null && { FS_OPT=true; rm -f /opt/.wt_probe_$$; } || true

$FS_HOME_WRITE || die "Cannot write to home directory ($HOME). Check permissions."
ok "Filesystem: home writable ✓  /usr/local writable: $FS_USR_LOCAL  /opt writable: $FS_OPT"

mkdir -p "$WT_CONFIG_DIR"
chmod 700 "$WT_CONFIG_DIR"
log_local "stage0" "preflight_pass" "home_write:$FS_HOME_WRITE usr_local:$FS_USR_LOCAL opt:$FS_OPT"

sleep 1

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 1 — Platform Detection
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Platform Detection" \
  "Finding your Linux distro and package manager"

ARCH="$(uname -m)"
ok "Architecture: $ARCH"

if [ -f /etc/os-release ]; then
  . /etc/os-release
  DISTRO="${ID:-unknown}"
  ok "Distro: ${PRETTY_NAME:-$DISTRO}"
else
  DISTRO="unknown"
  warn "Cannot detect distro (/etc/os-release missing)"
fi

if has apt-get; then
  PKG_MGR="apt"; PKG_INSTALL="sudo apt-get install -y"
  ok "Package manager: apt"
elif has dnf; then
  PKG_MGR="dnf"; PKG_INSTALL="sudo dnf install -y"
  ok "Package manager: dnf"
elif has pacman; then
  PKG_MGR="pacman"; PKG_INSTALL="sudo pacman -S --noconfirm"
  ok "Package manager: pacman"
elif has zypper; then
  PKG_MGR="zypper"; PKG_INSTALL="sudo zypper install -y"
  ok "Package manager: zypper"
else
  die "No supported package manager found (apt/dnf/pacman/zypper). Install one first."
fi

log_local "stage1" "detected" "distro:$DISTRO pkg:$PKG_MGR arch:$ARCH"
wt_svc_upsert "platform:linux" "null" "$DISTRO" "active" "$PKG_MGR/$ARCH"
sleep 0.5

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 2 — System Dependencies
# ═══════════════════════════════════════════════════════════════════════════════
step_header "System Dependencies" \
  "git, curl, build tools — required by Node.js and the MCP server"

install_pkg() {
  local pkg="$1" check="${2:-$1}"
  has "$check" && { ok "$pkg — already installed"; return 0; }
  info "Installing $pkg..."
  if retry 3 2 $PKG_INSTALL "$pkg" >/dev/null 2>&1; then
    has "$check" && ok "$pkg installed" || {
      fail "$pkg install appeared to succeed but binary not found — check PATH"
    }
  else
    fail "$pkg install failed. Try manually: $PKG_INSTALL $pkg"
  fi
}

case "$PKG_MGR" in
  apt)     $PKG_INSTALL build-essential curl git >/dev/null 2>&1 && ok "build-essential + curl + git" || fail "apt install failed" ;;
  dnf)     $PKG_INSTALL "@development-tools" curl git >/dev/null 2>&1 && ok "dev-tools + curl + git" || fail "dnf install failed" ;;
  pacman)  $PKG_INSTALL base-devel curl git >/dev/null 2>&1 && ok "base-devel + curl + git" || fail "pacman install failed" ;;
  zypper)  $PKG_INSTALL -t pattern devel_basis curl git >/dev/null 2>&1 && ok "devel_basis + curl + git" || fail "zypper install failed" ;;
esac

has git  || die "git not found after install — run: $PKG_INSTALL git"
has curl || die "curl not found after install — run: $PKG_INSTALL curl"
ok "git $(git --version | cut -d' ' -f3)"
ok "curl $(curl --version | head -1 | cut -d' ' -f2)"

log_local "stage2" "deps_ok" "git:$(git --version | cut -d' ' -f3)"

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 3 — Node.js via nvm
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Node.js v${WT_NODE_VERSION} LTS" \
  "Installed via nvm — portable, user-level, no sudo needed"

NVM_DIR="${NVM_DIR:-$HOME/.nvm}"

install_nvm() {
  info "Installing nvm..."
  if retry 3 3 curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash >/dev/null 2>&1; then
    export NVM_DIR="$HOME/.nvm"
    # shellcheck disable=SC1091
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
    has nvm && ok "nvm installed" || die "nvm installed but not loadable — open a new terminal and re-run"
  else
    die "nvm install failed after 3 attempts. Check: curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
  fi
}

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" || install_nvm

if has node; then
  CURRENT_NODE="$(node -v | tr -d 'v' | cut -d. -f1)"
  if [ "$CURRENT_NODE" -ge "$WT_NODE_VERSION" ]; then
    ok "Node.js $(node -v) — meets v${WT_NODE_VERSION}+ requirement"
  else
    warn "Node.js $(node -v) is below v${WT_NODE_VERSION}. Upgrading..."
    nvm install "$WT_NODE_VERSION" && nvm use "$WT_NODE_VERSION" && nvm alias default "$WT_NODE_VERSION" \
      && ok "Node.js upgraded to $(node -v)" \
      || die "nvm upgrade to v${WT_NODE_VERSION} failed"
  fi
else
  info "Installing Node.js v${WT_NODE_VERSION} LTS..."
  nvm install "$WT_NODE_VERSION" && nvm alias default "$WT_NODE_VERSION" \
    && ok "Node.js $(node -v)" \
    || die "nvm install v${WT_NODE_VERSION} failed. Try: nvm install $WT_NODE_VERSION"
fi

NODE_PATH="$(command -v node)"
NPM_PATH="$(command -v npm)"
ok "npm $(npm -v) at $NPM_PATH"

log_local "stage3" "node_ok" "version:$(node -v) path:$NODE_PATH"
wt_svc_upsert "runtime:node" "null" "$NODE_PATH" "active" "v$(node -v | tr -d 'v')"

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 4 — Claude Code CLI
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Claude Code" \
  "The AI assistant — installed globally via npm"

if has claude; then
  ok "Claude Code — already installed ($(claude --version 2>/dev/null || echo 'unknown version'))"
else
  info "Installing Claude Code..."
  if retry 3 5 npm install -g @anthropic-ai/claude-code --quiet 2>/dev/null; then
    has claude && ok "Claude Code installed" || die "Claude Code not found after install — check npm global path"
  else
    die "Claude Code install failed after 3 retries. Try: npm install -g @anthropic-ai/claude-code"
  fi
fi

CLAUDE_PATH="$(command -v claude)"
log_local "stage4" "claude_ok" "path:$CLAUDE_PATH"
wt_svc_upsert "cli:claude-code" "null" "$CLAUDE_PATH" "active" "$(claude --version 2>/dev/null | head -1)"

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 5 — wikiTaTa MCP Server
# ═══════════════════════════════════════════════════════════════════════════════
step_header "wikiTaTa MCP Server" \
  "The local bridge between Claude and your wikiTaTa workspace"

WT_REPO_DIR="$HOME/git/wikitata"

if [ -d "$WT_REPO_DIR/.git" ]; then
  ok "Repo found at $WT_REPO_DIR — pulling latest"
  ( cd "$WT_REPO_DIR" && git pull --quiet ) || warn "git pull failed — continuing with existing code"
else
  info "Cloning wikiTaTa repo..."
  mkdir -p "$HOME/git"
  if retry 3 5 git clone --depth 1 "$WT_MCP_REPO" "$WT_REPO_DIR" --quiet 2>/dev/null; then
    ok "Cloned to $WT_REPO_DIR"
  else
    die "git clone failed after 3 retries. Check SSH key or repo URL: $WT_MCP_REPO"
  fi
fi

MCP_SERVER_DIR="$WT_REPO_DIR/wt-mcp-server"
[ -d "$MCP_SERVER_DIR" ] || die "wt-mcp-server directory not found in repo at $WT_REPO_DIR"

info "Installing MCP server dependencies..."
if retry 3 10 npm install --prefix "$MCP_SERVER_DIR" --quiet 2>/dev/null; then
  ok "MCP server dependencies installed"
else
  warn "npm install failed — retrying with clean node_modules..."
  rm -rf "$MCP_SERVER_DIR/node_modules" "$MCP_SERVER_DIR/package-lock.json"
  if retry 2 10 npm install --prefix "$MCP_SERVER_DIR" --quiet 2>/dev/null; then
    ok "MCP server dependencies installed (after clean retry)"
  else
    die "MCP server npm install failed. Check: npm install --prefix $MCP_SERVER_DIR"
  fi
fi

log_local "stage5" "mcp_ok" "path:$MCP_SERVER_DIR"
wt_svc_upsert "mcp:wikitata-server" "null" "$MCP_SERVER_DIR/index.js" "active" ""

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 6 — Credential Storage
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Credential Storage" \
  "Storing your API tokens securely (keyring or encrypted config)"

WT_SECRETS_FILE="$WT_CONFIG_DIR/secrets"
CRED_BACKEND=""

# Prefer system keyring (GNOME/KDE) over file
if has secret-tool 2>/dev/null; then
  CRED_BACKEND="secret-tool"
  info "Using GNOME Keyring (secret-tool)"
  ok "Backend: system keyring"
elif has kwallet-query 2>/dev/null; then
  CRED_BACKEND="kwallet"
  info "Using KWallet"
  ok "Backend: KWallet"
else
  CRED_BACKEND="encrypted-file"
  warn "No system keyring found — using encrypted config file at $WT_SECRETS_FILE"
  info "(Install libsecret-tools or gnome-keyring for stronger storage)"
fi

# Store device_id in chosen backend (used by self-heal poller and clawd to identify this machine)
store_secret() {
  local name="$1" value="$2"
  case "$CRED_BACKEND" in
    secret-tool)
      printf '%s' "$value" | secret-tool store --label="wikiTaTa:$name" service wikitata key "$name" 2>/dev/null \
        && ok "Stored $name in GNOME Keyring" \
        || { warn "Keyring store failed for $name — falling back to encrypted file"; CRED_BACKEND="encrypted-file"; store_secret "$name" "$value"; }
      ;;
    encrypted-file)
      touch "$WT_SECRETS_FILE"; chmod 600 "$WT_SECRETS_FILE"
      # DPAPI-equivalent: encrypt with user's own key derived from machine+uid
      local salt="wikitata-$(id -u)-$(hostname)"
      local encrypted
      encrypted=$(printf '%s' "$value" | openssl enc -aes-256-cbc -pbkdf2 -pass "pass:$salt" -base64 2>/dev/null) \
        || { warn "openssl encryption failed — storing as locked file (chmod 600 only)"; encrypted="$value"; }
      printf '%s=%s\n' "$name" "$encrypted" >> "$WT_SECRETS_FILE"
      ok "Stored $name in $WT_SECRETS_FILE (600)"
      ;;
  esac
}

[ -n "$WT_DEVICE_ID" ] && store_secret "WT_DEVICE_ID" "$WT_DEVICE_ID" || warn "WT_DEVICE_ID empty — skipping credential storage"

log_local "stage6" "creds_ok" "backend:$CRED_BACKEND"
wt_svc_upsert "credential:backend" "null" "$CRED_BACKEND" "active" "$WT_SECRETS_FILE"

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 7 — Claude MCP Registration
# ═══════════════════════════════════════════════════════════════════════════════
step_header "MCP Registration" \
  "Wiring the wikiTaTa MCP server into Claude Code"

CLAUDE_JSON="$HOME/.claude.json"

mcp_already_registered() {
  [ -f "$CLAUDE_JSON" ] && grep -q "wikitata" "$CLAUDE_JSON" 2>/dev/null
}

if mcp_already_registered; then
  ok "wikiTaTa MCP already registered in ~/.claude.json"
else
  blank
  info "This will add the wikiTaTa MCP server to your Claude Code config."
  info "File: $CLAUDE_JSON"
  if confirm "Register wikiTaTa MCP server in Claude Code?"; then
    if claude mcp add -s user wikitata node "$MCP_SERVER_DIR/index.js" 2>/dev/null; then
      ok "MCP registered via claude mcp add"
    else
      warn "claude mcp add failed — writing to ~/.claude.json directly..."
      node "$WT_REPO_DIR/wt-mcp-server/scripts/register-mcp.js" 2>/dev/null \
        && ok "MCP registered via register-mcp.js" \
        || fail "MCP registration failed — run manually: claude mcp add -s user wikitata node $MCP_SERVER_DIR/index.js"
    fi
  else
    warn "MCP registration skipped — run later: claude mcp add -s user wikitata node $MCP_SERVER_DIR/index.js"
  fi
fi

log_local "stage7" "mcp_registered" "path:$MCP_SERVER_DIR"

# ── Golden-bootstrap seed: self-healing config sync (card 2aae217c, Part B) ──
# Fetches the SIGNED golden hook bundle, verifies vs the pinned key, installs the bootstrap,
# and wires a SessionStart hook so every future session parity-checks config. Idempotent.
SEED_MJS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/install-golden-bootstrap.mjs"
if [ -f "$SEED_MJS" ]; then
  if WT_ACTOR="$WT_USERNAME" node "$SEED_MJS" 2>/dev/null; then
    ok "Golden-bootstrap seed installed — SessionStart parity check wired (card 2aae217c)"
  else
    warn "Golden-bootstrap seed skipped — run later: WT_ACTOR=$WT_USERNAME node $SEED_MJS"
  fi
  log_local "stage7b" "golden_seed" "installed"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 8 — Port Discovery & Service Registration
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Port Discovery" \
  "Finding free ports for local services — stored in your wikiTaTa config"

SPINE_PORT=$(find_free_port 5173 5183)
MCP_PORT=$(find_free_port 3737 3750)
DEV_PORT=$(find_free_port 3000 3030)

ok "Local spine port:  $SPINE_PORT"
ok "MCP server port:   $MCP_PORT"
ok "Dev server port:   $DEV_PORT"

# Write discovered ports to config file
WT_PORT_FILE="$WT_CONFIG_DIR/ports.json"
printf '{"spine":%d,"mcp":%d,"dev":%d,"discovered_at":"%s","platform":"%s"}\n' \
  "$SPINE_PORT" "$MCP_PORT" "$DEV_PORT" \
  "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$PLATFORM" > "$WT_PORT_FILE"
ok "Port config written to $WT_PORT_FILE"

# Write to DB
wt_svc_upsert "local:spine" "$SPINE_PORT" "$WT_REPO_DIR" "active" "sveltekit-dev"
wt_svc_upsert "local:mcp" "$MCP_PORT" "$MCP_SERVER_DIR/index.js" "active" "stdio-mcp"
wt_svc_upsert "local:dev" "$DEV_PORT" "$WT_REPO_DIR" "active" "dev-server"

log_local "stage8" "ports_ok" "spine:$SPINE_PORT mcp:$MCP_PORT dev:$DEV_PORT"

# Device already registered in user_devices by activate Edge Function at Stage 0.
ok "Device ID: ${WT_DEVICE_ID} (registered during activation)"
log_local "stage8" "device_confirmed" "id:${WT_DEVICE_ID}"

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 9 — Live Validation
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Live Validation" \
  "Confirming Node, Claude, and MCP are fully wired"

VALIDATION_ERRORS=0

node -e "console.log('ok')" 2>/dev/null | grep -q ok \
  && ok "Node.js runtime: ok" \
  || { fail "Node.js runtime check failed"; VALIDATION_ERRORS=$((VALIDATION_ERRORS + 1)); }

has claude \
  && ok "Claude Code CLI: ok" \
  || { fail "Claude Code CLI not found"; VALIDATION_ERRORS=$((VALIDATION_ERRORS + 1)); }

[ -f "$MCP_SERVER_DIR/index.js" ] \
  && ok "MCP server: index.js present" \
  || { fail "MCP server index.js missing at $MCP_SERVER_DIR"; VALIDATION_ERRORS=$((VALIDATION_ERRORS + 1)); }

node -e "require('$MCP_SERVER_DIR/index.js')" 2>/dev/null && {
  ok "MCP server: loads without syntax errors"
} || {
  warn "MCP server syntax check failed — trying npm install again..."
  npm install --prefix "$MCP_SERVER_DIR" --quiet 2>/dev/null && ok "MCP server: deps fixed" \
    || { fail "MCP server still fails to load"; VALIDATION_ERRORS=$((VALIDATION_ERRORS + 1)); }
}

if [ "$VALIDATION_ERRORS" -eq 0 ]; then
  log_local "stage9" "validation_pass" "all_ok"
  wt_svc_upsert "onboard:status" "null" "$WT_CONFIG_DIR" "active" "linux_complete"
else
  log_local "stage9" "validation_fail" "errors:$VALIDATION_ERRORS"
  warn "$VALIDATION_ERRORS validation check(s) failed — see errors above"
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 9.5 — Self-Heal Handshake (card ce413352 — config-server handshake)
# Installs the per-machine self-heal poller (user-level systemd), generates the
# device token (plaintext NEVER leaves this machine; only its sha256 registers),
# and submits the first boot-audit so the machine is remotely diagnosable from
# first boot. Best-effort: a failure here warns + logs, never blocks onboarding.
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Self-Heal Handshake" \
  "Registering this machine for remote diagnostics + allowlisted self-repair"

SELFHEAL_OK=1
SELFHEAL_DIR="$WT_REPO_DIR/tools/self-heal"
SELFHEAL_CFG="$WT_CONFIG_DIR/selfheal.json"
# SELFHEAL_TOKEN_FILE was generated at Stage 0; hash was registered with activate EF.

if [ -z "$WT_DEVICE_ID" ]; then
  warn "Self-heal handshake skipped (no device id) — re-run after activation"
  log_local "stage9.5" "skipped" "no_device_id"
  SELFHEAL_OK=0
elif [ ! -f "$SELFHEAL_DIR/poller.js" ]; then
  warn "Self-heal handshake skipped (tools/self-heal missing in repo checkout)"
  log_local "stage9.5" "skipped" "no_selfheal_dir"
  SELFHEAL_OK=0
fi

if [ "$SELFHEAL_OK" -eq 1 ]; then
  # Device token was generated at Stage 0 (SELFHEAL_TOKEN_FILE); hash registered by activate EF.
  ok "Device token: ${SELFHEAL_TOKEN_FILE} (hash registered at activation)"

  # Config (token_file override — user-level install, no /etc access).
  printf '{\n  "device_id": "%s",\n  "supabase_url": "%s",\n  "anon_key": "%s",\n  "token_file": "%s",\n  "poll_seconds": 30,\n  "burst_seconds": 5,\n  "units": {},\n  "repos": ["%s"],\n  "expected_keychain_keys": ["%s"]\n}\n' \
    "$WT_DEVICE_ID" "$WT_SB_URL" "$WT_SB_ANON_KEY" "$SELFHEAL_TOKEN_FILE" "$WT_REPO_DIR" "$SELFHEAL_TOKEN_FILE" > "$SELFHEAL_CFG"
  if node -e "JSON.parse(require('fs').readFileSync(process.argv[1],'utf8'))" "$SELFHEAL_CFG" 2>/dev/null; then
    ok "Self-heal config written ($SELFHEAL_CFG)"
    log_local "stage9.5" "config_ok" "$SELFHEAL_CFG"
  else
    warn "Self-heal config invalid — handshake aborted"
    log_local "stage9.5" "config_fail" "$SELFHEAL_CFG"
    SELFHEAL_OK=0
  fi
fi

if [ "$SELFHEAL_OK" -eq 1 ]; then
  # 4) systemd USER unit (no root needed) + linger so it survives logout.
  SYSTEMD_USER_DIR="$HOME/.config/systemd/user"
  mkdir -p "$SYSTEMD_USER_DIR"
  NODE_BIN_SH=$(command -v node)
  printf '[Unit]\nDescription=wikiTaTa self-heal poller (card ce413352)\nAfter=network-online.target\n\n[Service]\nType=simple\nEnvironment=WT_SELFHEAL_CONFIG=%s\nExecStart=%s %s/poller.js\nRestart=always\nRestartSec=5\n\n[Install]\nWantedBy=default.target\n' \
    "$SELFHEAL_CFG" "$NODE_BIN_SH" "$SELFHEAL_DIR" > "$SYSTEMD_USER_DIR/wt-selfheal.service"
  if systemctl --user daemon-reload 2>/dev/null && systemctl --user enable --now wt-selfheal.service 2>/dev/null; then
    ok "Self-heal poller running (systemd --user wt-selfheal.service)"
    loginctl enable-linger "$USER" 2>/dev/null \
      && ok "Linger enabled — poller survives logout" \
      || warn "Could not enable linger — poller runs only while you are logged in"
    log_local "stage9.5" "poller_ok" "systemd-user"
    wt_svc_upsert "selfheal:poller" "null" "$SELFHEAL_DIR/poller.js" "active" "systemd-user"
  else
    warn "systemd --user unavailable — poller not started (container/WSL without user bus?)"
    log_local "stage9.5" "poller_fail" "no_systemd_user"
    SELFHEAL_OK=0
  fi
fi

if [ "$SELFHEAL_OK" -eq 1 ]; then
  # 5) First boot-audit → the machine's full config snapshot lands server-side.
  if WT_SELFHEAL_CONFIG="$SELFHEAL_CFG" node "$SELFHEAL_DIR/boot-audit.js" --trigger install >/dev/null 2>&1; then
    ok "Boot config-audit submitted — machine is remotely diagnosable"
    log_local "stage9.5" "audit_ok" "install"
  else
    warn "Boot audit failed (poller will retry at startup)"
    log_local "stage9.5" "audit_fail" "install"
  fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 10 — MCP-Verified Handshake (ONBOARD-M6, task f8c367c2, north-star 8c047748 §5)
# Final gate: ask the LIVE MCP server (mcp.wikitata.com) to confirm this exact
# (user, device) pair resolves to a real wikiTaTa account with a usable config,
# and report platform health. The verdict prints HERE, before the terminal is
# done — a hard failure (server unreachable / device unknown / account missing)
# exits non-zero immediately so nothing pretends the install worked.
# ═══════════════════════════════════════════════════════════════════════════════
step_header "MCP-Verified Handshake" \
  "Confirming Claude can see your wikiTaTa account — live, end-to-end"

WT_MCP_BASE="${WT_MCP_BASE:-https://mcp.wikitata.com}"

[ -n "$WT_DEVICE_ID" ] || {
  log_local "stage10" "verify_fail" "no_device_id"
  blank
  fail "NOT VERIFIED — no device id from activation; cannot run the handshake."
  info "Remedy: re-run the personalized one-liner from start.wikitata.com/onboard"
  info "Help: request a new activation link at start.wikitata.com/request-token"
  exit 1
}

VERIFY_URL="${WT_MCP_BASE}/health/first-connect?user=${WT_USERNAME}&device=${WT_DEVICE_ID}"
VERIFY_RESP=""
info "Contacting ${WT_MCP_BASE} ..."
# NOTE: curl WITHOUT -f — a 404 verdict (device not recognized) carries its
# remedy in the JSON body, which we want to read, not discard.
_v=1
while [ "$_v" -le 3 ]; do
  VERIFY_RESP=$(curl -s --max-time 15 "$VERIFY_URL" 2>/dev/null) || VERIFY_RESP=""
  [ -n "$VERIFY_RESP" ] && break
  [ "$_v" -lt 3 ] && { warn "Handshake attempt $_v/3 failed — retrying in 3s..."; sleep 3; }
  _v=$((_v + 1))
done

if [ -z "$VERIFY_RESP" ]; then
  log_local "stage10" "verify_unreachable" "$WT_MCP_BASE"
  blank
  fail "NOT VERIFIED — could not reach the wikiTaTa MCP server after 3 attempts."
  info "Remedy: check your internet connection, then re-run just the check:"
  dim "  curl \"$VERIFY_URL\""
  info "Help: re-run the one-liner from start.wikitata.com/onboard, or contact support"
  exit 1
fi

if printf '%s' "$VERIFY_RESP" | grep -q '"ok":true'; then
  PROBES_GREEN=$(printf '%s' "$VERIFY_RESP" | grep -oE '"probes_green":[0-9]+' | grep -oE '[0-9]+' | head -1 || true)
  PROBES_TOTAL=$(printf '%s' "$VERIFY_RESP" | grep -oE '"probes_total":[0-9]+' | grep -oE '[0-9]+' | head -1 || true)
  PROBES_MSG="health probes not reported"
  [ -n "${PROBES_GREEN:-}" ] && [ -n "${PROBES_TOTAL:-}" ] && PROBES_MSG="${PROBES_GREEN}/${PROBES_TOTAL} health probes green"
  blank
  printf "  ${G}${BD}✅ VERIFIED — Claude can see your wikiTaTa account (%s): config OK, %s. Open Claude and say hello.${RST}\n" \
    "$WT_USERNAME" "$PROBES_MSG"
  log_local "stage10" "verify_pass" "probes:${PROBES_GREEN:-?}/${PROBES_TOTAL:-?}"
  wt_svc_upsert "onboard:verified" "null" "$WT_MCP_BASE" "active" "first-connect-handshake"
else
  VERIFY_ERR=$(printf '%s' "$VERIFY_RESP" | grep -oE '"error":"[^"]+"' | head -1 | cut -d'"' -f4)
  VERIFY_REMEDY=$(printf '%s' "$VERIFY_RESP" | grep -oE '"remedy":"[^"]+"' | head -1 | cut -d'"' -f4)
  log_local "stage10" "verify_fail" "${VERIFY_ERR:-unknown_error}"
  blank
  fail "NOT VERIFIED — failed gate: ${VERIFY_ERR:-unknown_error}"
  info "Remedy: ${VERIFY_REMEDY:-Re-run the personalized one-liner from start.wikitata.com/onboard}"
  info "Help: request a new activation link at start.wikitata.com/request-token, or contact support"
  exit 1
fi

# ═══════════════════════════════════════════════════════════════════════════════
# STAGE 11 — Final Report
# ═══════════════════════════════════════════════════════════════════════════════
step_header "Complete" \
  "wikiTaTa is set up on this Linux machine"

blank
if [ "$ERRORS" -eq 0 ] && [ "$VALIDATION_ERRORS" -eq 0 ]; then
  printf "  ${G}${BD}✓ PASS — Everything installed and verified.${RST}\n"
else
  printf "  ${Y}${BD}⚠ DONE with %d error(s) — see above.${RST}\n" "$((ERRORS + VALIDATION_ERRORS))"
fi
blank
# Re-print the handshake verdict — step_header cleared the screen, and this
# line is the one that must survive until the user reads it (ONBOARD-M6).
printf "  ${G}${BD}✅ VERIFIED — Claude can see your wikiTaTa account (%s): config OK, %s. Open Claude and say hello.${RST}\n" \
  "$WT_USERNAME" "$PROBES_MSG"
blank
printf "  ${BD}What's set up:${RST}\n"
dim "  Node.js:       $(node -v 2>/dev/null || echo 'see above')"
dim "  Claude Code:   $(command -v claude 2>/dev/null || echo 'see above')"
dim "  MCP server:    $MCP_SERVER_DIR"
dim "  Local spine:   port $SPINE_PORT"
dim "  Config dir:    $WT_CONFIG_DIR"
dim "  Install log:   $WT_LOCAL_LOG"
blank
printf "  ${BD}Next steps:${RST}\n"
info "Start a new terminal session (loads nvm PATH)"
info "Run: claude (opens Claude Code)"
info "In Claude: say 'hello' — wt_session_start runs automatically"
info "Visit: my.wikitata.com — your workspace is ready"
blank
dim "All install events logged to $WT_LOCAL_LOG"
[ -n "$WT_DEVICE_ID" ] && dim "Device registered in wikiTaTa — visible in Settings → Devices"
blank
